SaliencySlider/GradCam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

# in case Django has many apps, this differentiates them
app_name = "GradCam"

urlpatterns = [
    path("", views.index, name="index"),
    path("display_image/", views.display_image, name="display_image"),
    path("user_image/", views.user_image, name="user_image"),
    path("success/", views.success, name='success'),
    path('raw_images/', views.display_raw_images, name = 'raw_images'),
    path('last_image/', views.display_last_image, name="last_image"),
    path('update_image/', views.update_image, name='update_image'),
]
 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


 # 
    # path("<int:question_id>/", views.detail, name="detail"), # ex: /polls/5/
    # path("<int:question_id>/results/", views.results, name="results"), # ex: /polls/5/results/
    # path("<int:question_id>/vote/", views.vote, name="vote"), # ex: /polls/5/vote/

SaliencySlider/SaliencySlider/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path("admin/", admin.site.urls),
    path("GradCam/", include("GradCam.urls")) # you should always use include, except with admin ^
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

SaliencySlider/GradCam/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

# class that allows users to upload their images so they can be used in the program
class UserImage(models.Model):
    image = models.ImageField(upload_to="user_images/")
    upload_date = models.DateTimeField(auto_now_add=True)
    
'''
# we now need to tell the overall program that this app (gradcam) exists
# go to SaliencySlider/settings.py and add "GradCam.apps.GradcamConfig" under INSTALLED_APPS
# we then execute $python manage.py makemigrations GradCam
# $python manage.py migrate  basically syncs up and applies any unapplied changes

# 3 Steps for making model changes:
    * Change your models (in models.py).
    * Run python manage.py makemigrations to create migrations for those changes
    * Run python manage.py migrate to apply those changes to the database.
'''









# # classes here subclass django.db.models.Model
# class Question(models.Model):
#     question_text = models.CharField(max_length=200) # some field classes have required arguments
#     pub_date = models.DateTimeField("date published") # you can pass a human-readable name as an argument

#     # now the question text is displayed when $Question.objects.all() is called
#     def __str__(self):
#         return self.question_text
    
#     # can replace this with my actual functions later
#     def was_published_recently(self):
#         return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE) # one-to-one, many-to-many or many-to-one relationships
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0) # some fields have optional arguments

#     def __str__(self):
#         return self.choice_text




SaliencySlider/GradCam/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import UserImage
import os

class UserImageForm(forms.ModelForm):

    class Meta:
        model = UserImage
        fields = ['image']

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            # checks the file extension
            ext = os.path.splitext(image.name)[1].lower()  # Get the file extension
            valid_extensions = ['.png', '.jpg', '.jpeg']
            if not ext.lower() in valid_extensions:
                raise ValidationError('Unsupported file extension.')
        return image

SaliencySlider/GradCam/views.py
import json
from django.db.models import F
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404 # to raise 404 errors
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader # eg. template = loader.get_template("GradCam/index.html")
from django.urls import reverse
from django import forms
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse

from .models import UserImage
from .forms import UserImageForm
from .image_processor import process_image

def index(request):
    print('hi I am the index')
    return render(request, 'GradCam/index.html')

# test function to display a placeholder image
def display_image(request):
    # find a way to update this dynamically
    image_path = "apple.jpg"

    with open(image_path, 'rb') as image:
        return HttpResponse(image.read(), content_type="image/png")
    

def user_image(request):
    # check if request is POST -- data is submitted
    print('user tried submitting file')
    if request.method == 'POST':
        form = UserImageForm(request.POST, request.FILES)
        
        # checks if all required fields in the form are filled
        if form.is_valid():
            form.save() # saves the form data into database
            return redirect('GradCam:last_image')
        
    # if form is invalid, it just retries it
    else:
        form = UserImageForm()

    return render(request, 'GradCam/index.html', {'form': form})   
    
def success(request):
    return HttpResponse('successfully uploaded')
    
def display_raw_images(request):
    if request.method == 'GET':

        UserImages = UserImage.objects.all()
        return render(request, 'GradCam/display_raw_images.html',
                       {'raw_images': UserImages})

def display_last_image(request):
    if request.method == 'GET':
        # '-upload_date' orders descending, 'first()' gets the most recent
        last_image = UserImage.objects.order_by('-upload_date').first()  
        return render(request, 'GradCam/display_last_image.html', {'last_image': last_image})

def update_image(request):
    try:
        if request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            data = json.loads(request.body)
            intensity = data.get('intensity', 0)
            image_path = data.get('image_path', '')
            print("Received intensity:", intensity)  # Debugging output
            print("Received image path:", image_path)  # Debugging output

            if not image_path:
                return JsonResponse({'error': 'Image path is empty'}, status=400)

            image_data_url, highest_pred_label = process_image(image_path, int(intensity))
            return JsonResponse({
                'image_data_url': image_data_url,
                'predicted_class': highest_pred_label  # Add this line to return the predicted class
            })
        else:
            return JsonResponse({'error': 'Invalid request'}, status=400)
    except Exception as e:
        print("Error processing image:", e)  # More detailed error logging
        return JsonResponse({'error': str(e)}, status=500)
        
# # Create your views here.
# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     # now we can use the html template we created
#     context = {"latest_question_list": latest_question_list}
#     return render(request, "GradCam/index.html", context) # returns HttpResponse object

# # slightly different because it takes an argument
# def detail(request, question_id):
#     # raises Http404 if object is not found
#     question = get_object_or_404(Question, pk=question_id) # could be get_list_or_404 to check for empty list
#     return render(request, "GradCam/detail.html", {"question": question})

# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST["choice"]) # request.POST values r always strings
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(
#             request,
#             "GradCam/detail.html",
#             {
#                 "question": question,
#                 "error_message": "You didn't select a choice.",
#             },
#         )
#     else:
#         selected_choice.votes = F("votes") + 1
#         selected_choice.save()
        
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse("GardCam:results", args=(question.id,)))  


SaliencySlider/GradCam/templates/GradCam/display_last_image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Processor</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            text-align: center;
            background-color: #ffffff;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            width: 80%; /* Adjust width to fit content better */
            max-width: 600px; /* Limit the maximum width */
        }
        h1 {
            color: #333;
        }
        label {
            display: block;
            margin-top: 20px;
            color: #555;
            font-size: 18px;
        }
        input[type="range"] {
            width: 100%;
            margin: 10px 0;
        }
        img {
            max-width: 100%; /* Ensures the image does not exceed the container width */
            height: auto;
            border-radius: 8px; /* Optional: adds rounded corners to the image */
        }
        p#predicted-class {
            color: #666;
            font-size: 20px;
            margin-top: 20px; /* Adjust spacing as needed */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to Saliency Slider</h1>
        <label for="intensity-slider">Feature Saliency Percentage: <span id="intensity-value">0</span>%</label>
        <input type="range" id="intensity-slider" min="0" max="100" value="0" step="1">
        <img id="image-display" src="{{ last_image.image.url }}" alt="Processed Image">
        <p id="predicted-class">Predicted Class: <span id="class-label">N/A</span></p>
        
        <script>
            const intensitySlider = document.getElementById('intensity-slider');
            const intensityValueDisplay = document.getElementById('intensity-value');
            const imageDisplay = document.getElementById('image-display');
            const classLabelDisplay = document.getElementById('class-label');
            const originalImageUrl = imageDisplay.src;  // Store the original image URL
        
            intensitySlider.addEventListener('input', function() {
                intensityValueDisplay.textContent = this.value;
                
                fetch('{% url "GradCam:update_image" %}', {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                        'Content-Type': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest'
                    },
                    body: JSON.stringify({ intensity: this.value, image_path: originalImageUrl })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.image_data_url && 'predicted_class' in data) {
                        // Update the displayed image src with the new base64 data URL
                        imageDisplay.src = data.image_data_url;
                        classLabelDisplay.textContent = data.predicted_class; // Update the predicted class label
                    } else {
                        console.error('Error:', data.error);
                    }
                })
                .catch(error => console.error('Error:', error));
            });
        </script>
    </div>
</body>
</html>

SaliencySlider/GradCam/templates/GradCam/display_raw_images.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Raw Images</title>
 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
</head>
<body>
 
    {% for image in raw_images %}
            <div class="col-md-4">
                   
                    <img src="{{ image.image.url }}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" />
            </div>
    {% endfor %}
 
</body>
</html>

SaliencySlider/GradCam/templates/GradCam/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            text-align: center;
            background-color: #ffffff;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
        }
        p {
            color: #555;
        }
        button {
            background-color: #007BFF;
            color: white;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to Saliency Slider</h1>
        <p>Decisions from AI models can often seem opaque. <br> 
            Saliency methods highlight which parts of an image are most influential. <br>
            Upload your own images below and explore the power of explainable AI.
            <form action="{% url 'GradCam:user_image' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="image" id="image" required>
                <button type="submit">Upload Image</button>
            </form>
    </div>
</body>
</html>

SaliencySlider/GradCam/templates/GradCam/upload_image.html
{% extends "GradCam/base_generic.html" %}
{% block content %}
    <h2>Upload an Image</h2>
    <form action="{% url 'GradCam:user_image' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="image" id="image" required  accept="image/png, image/jpeg, image/jpg">
        <button type="submit">Upload</button>
    </form>
    {% if uploaded_image_url %}
        <p>Image uploaded successfully!</p>
        <img src="{{ uploaded_image_url }}" alt="Uploaded Image">
    {% endif %}
{% endblock %}